
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped


  geoserver:
    image: kartoza/geoserver:2.23.2
    container_name: geoserver
    ports:
      - "${GEOSERVER_PORT}:8080"
    environment:
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=geoserver
    volumes:
      - ./infra/geoserver/data_dir:/opt/geoserver/data_dir
    depends_on:
      - postgres
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    env_file: .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio:/data
    restart: unless-stopped

  api:
    build: ./services/api
    container_name: api
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    restart: unless-stopped

  opcua-bridge:
    build: ./services/opcua-bridge
    container_name: opcua-bridge
    env_file: .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  web:
    build: ./web
    container_name: web
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
  minio:
